######################## default configuration ####################
baseURL = "/"
title = "Truth in History | Teaching the revelations of Jesus Christ as Prophet, Priest, and King"
theme = "logbook"
# post pagination
paginate = "8"
# post excerpt
summaryLength = "50"
# google analytics
googleAnalytics = "" # Ex: UA-123-45
# disqus short name
disqusShortname = "#" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["Fr"] # desable language from here

############################# Modules ##############################
[module]
[module.hugoVersion]
extended = true
# min = "0.89.4"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90


############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe= true

[markup.highlight]
style = 'monokai' # see https://xyproto.github.io/splash/docs/all.html

############################ Media types ############################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]


############################ Output Format ###########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
